#!/bin/bash

# Copyright (c) 2024  Teddy Wing
#
# This file is part of github-review-stats.
#
# github-review-stats is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# github-review-stats is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with github-review-stats. If not, see
# <https://www.gnu.org/licenses/>.


set -e

EX_USAGE=64

if [ $# -ne 3 ]; then
	echo >&2 'usage: github-review-stats-run <github-token> <since-date> <github-owner/repo>'
	exit $EX_USAGE
fi

token="$1"
since="$2"
owner_repo="$3"
repo="${owner_repo#*/}"

python github-fetch-pull-requests --token="$token" --since="$since" "$owner_repo"
mkdir "${repo}-reviews"
python github-fetch-reviews --token="$token" --since="$since" "${repo}.json" "${repo}-reviews"
python github-review-stats "${repo}.json" "${repo}-reviews"
