#!/bin/bash

# Copyright (c) 2024  Teddy Wing
#
# This file is part of github-review-stats.
#
# github-review-stats is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# github-review-stats is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with github-review-stats. If not, see
# <https://www.gnu.org/licenses/>.


set -e

EX_USAGE=64

if [ $# -ne 2 ]; then
	echo >&2 'usage: github-fetch-additions-deletions <pull-requests-file> <since>'
	exit $EX_USAGE
fi

pull_requests_file="$1"
since="$2"
since_timestamp="$(date -j -f "%F" "$since" +'%s')"

prs="$(jq \
	--compact-output \
	'.[] | {url: .html_url, created_at: .created_at}' \
	"$pull_requests_file"
)"


repo_name="$(jq --raw-output '.[0].base.repo.name' "$pull_requests_file")"
output_directory="${repo_name}-additions-deletions"
mkdir -p "$output_directory"

for pr in $prs; do
	pr_created_at="$(echo "$pr" \
		| jq \
			--raw-output \
			'.created_at'
	)"
	pr_created_timestamp="$(date -j -f "%FT%TZ" "$pr_created_at" +'%s')"

	if [ "$pr_created_timestamp" -le "$since_timestamp" ]; then
		break
	fi

	pr_url="$(echo "$pr" | jq --raw-output '.url')"

	output_file="${output_directory}/${pr_url##*/}.json"
	if [ -f "$output_file" ]; then
		continue
	fi

	gh pr view \
		--json=additions,deletions \
		"$pr_url" \
	> "$output_file"
done
