#!/usr/bin/env python

import argparse
import json

import requests


def github_request(token, endpoint, params={}):
    req = requests.get(
        f"https://api.github.com{endpoint}",
        headers={
            'Accept': 'application/vnd.github+json',
            'X-GitHub-Api-Version': '2022-11-28',
            'Authorization': f"Bearer {token}",
        },
        params=params,
    )

    return req


def fetch_pull_requests(token, owner_repo):
    collected_prs = []

    resp = github_request(
        token,
        f"/repos/{owner_repo}/pulls",
        params={
            'state': 'closed',
            'sort': 'created',
            'direction': 'desc',
            'per_page': 3,
        }
    )

    prs = resp.json()
    collected_prs = collected_prs + prs

    collected_prs_json = json.dumps(collected_prs)

    output_filename = owner_repo.split('/')[-1]
    with open(f"{output_filename}.json", 'w') as f:
        print(collected_prs_json, file=f)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Get statistics for GitHub code reviews',
    )
    parser.add_argument(
        '--token',
        required=True,
        help='GitHub token',
    )
    parser.add_argument('owner_repo')

    args = parser.parse_args()

    fetch_pull_requests(args.token, args.owner_repo)
